# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: ublue-kinoite-nvidia-hci
# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/ublue-os/kinoite-nvidia
# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: latest
# This description will be visible in the container metadata
description: Universal Blue Kinoite NVIDIA official image + plus virtualization tools, Sublime Text and multimedia codecs
# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
#  - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
# example:
# - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-37/atim-starship-fedora-37.repo

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  # needed for yafti (the first boot installer) (remove if you're not using yafti)
  #- python3-pip
  - libadwaita # libadwaita comes with silverblue, but not with other flavors
  # KDE
  - bismuth
  # HCI / virtualization
  - bridge-utils
  - edk2-ovmf
  - guestfs-tools
  - libguestfs-tools
  - libvirt
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - libvirt-devel
  - qemu-kvm
  - virt-install
  - virt-manager
  - virt-top
  - virt-viewer
  # Multimedia
  - mozilla-openh264
  # Other
  - syncthing
# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - com.bitwarden.desktop
  - com.borgbase.Vorta
  - com.brave.Browser
  - com.github.micahflee.torbrowser-launcher
  - com.github.tchx84.Flatseal
  - com.ktechpit.ultimate-media-downloader
  - com.slack.Slack
  - com.todoist.Todoist
  - dev.k8slens.OpenLens
  - im.riot.Riot
  - io.github.NhekoReborn.Nheko
  - io.github.aandrew_me.ytdn
  - io.github.spacingbat3.webcord
  - io.mpv.Mpv
  - org.gimp.GIMP
  - org.kde.akregator
  - org.kde.neochat
  - org.keepassxc.KeePassXC
  - org.nickvision.tubeconverter
  - org.nicotine_plus.Nicotine
  - org.remmina.Remmina
  - org.telegram.desktop
  - org.telegram.desktop.webview
  - us.zoom.Zoom
