default:
  @just --list

changelogs:
  rpm-ostree db diff --changelogs

distrobox-boxkit:
  echo 'Creating Boxkit distrobox ...'
  distrobox create --image ghcr.io/ublue-os/boxkit -n boxkit -Y

setup-flatpaks:
  #!/bin/bash
  echo 'Installing flatpaks from the ublue recipe ...'
  flatpaks=$(yq '.flatpaks[]' < /usr/etc/ublue-recipe.yml)
  for pkg in $flatpaks; do \
      echo "Installing: ${pkg}" && \
      flatpak install --user --noninteractive flathub $pkg; \
  done

cleanup-flatpak:
  flatpak remove --unused

setup-pwa:
  echo 'Giving browser permission to create PWAs (Progressive Web Apps)'
  # Add for your favorite chromium-based browser
  flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.microsoft.Edge

#nix-me-up:
#  echo 'Setting phasers to kill. Installing nix.'
#  /usr/bin/ublue-nix-install

set-kargs:
  rpm-ostree kargs \
    --append=rd.driver.blacklist=nouveau \
    --append=modprobe.blacklist=nouveau \
    --append=nvidia-drm.modeset=1 \
    --append=mem_sleep_default=deep \
    --append=initcall_blacklist=simpledrm_platform_driver_init

rpm-fusion:
  rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && rpm-ostree install gstreamer1-plugin-openh264 openh264

update:
  #!/bin/bash
  echo "Staging system update..."
  rpm-ostree update

  echo "Updating Flatpaks..."
  flatpak update -y

  echo "Updating Distroboxes..."
  distrobox upgrade -a
